[package]
name = "kurai_parser_import_file"
version = "0.2.0"
edition = "2024"

[dependencies]
kurai_token = { version = "0.2.0", path = "../kurai_token/" }
kurai_stmt = { version = "0.2.0", path = "../kurai_stmt/" }
