[workspace]
members = [
  "kurai",
  "kurai_core",
  "kurai_codegen",
  "stdlib"
]

# [dependencies]
# colored = "3.0.0"
# inkwell = { version = "0.5.0", features = ["llvm18-0"] }
# once_cell = "1.21.3"
