[package]
name = "kurai_core"
version = "0.4.3"
edition = "2024"

[dependencies]
kurai_expr = { version = "0.4.3", path = "../kurai_expr" }
kurai_types = { version = "0.4.3", path = "../kurai_types" }
