[package]
name = "kurai_token"
version = "0.4.9"
edition = "2024"

[dependencies]
kurai_ast = { version = "0.4.9", path = "../kurai_ast" }
kurai_stmt = { version = "0.4.9", path = "../kurai_stmt/" }
kurai_types = { version = "0.4.9", path = "../kurai_types" }
