[package]
name = "kurai_token"
version = "0.4.6"
edition = "2024"

[dependencies]
kurai_stmt = { version = "0.4.6", path = "../kurai_stmt/" }
kurai_types = { version = "0.4.6", path = "../kurai_types" }
