[package]
name = "vyn_core"
version = "0.4.9"
edition = "2024"

[dependencies]
vyn_ast = { version = "0.4.9", path = "../vyn_ast" }
vyn_expr = { version = "0.4.9", path = "../vyn_expr" }
vyn_types = { version = "0.4.9", path = "../vyn_types" }
