[package]
name = "stdlib"
version = "0.2.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
kurai_codegen = { version = "0.2.0", path = "../kurai_codegen" }
kurai_core = { version = "0.2.0", path = "../kurai_core" }
