[package]
name = "kurai_expr"
version = "0.4.6"
edition = "2024"

[dependencies]
kurai_types = { version = "0.4.6", path = "../kurai_types/" }
kurai_binop = { version = "0.4.6", path = "../kurai_binop/" }
