[package]
name = "kurai_expr"
version = "0.3.4"
edition = "2024"

[dependencies]
kurai_types = { version = "0.3.4", path = "../kurai_types/" }
kurai_binop = { version = "0.3.4", path = "../kurai_binop/" }
