[package]
name = "vyn_error"
version = "0.4.9"
edition = "2024"

[dependencies]
colored = "3.0.0"
vyn_token = { version = "0.4.9", path = "../vyn_token" }
vyn_types = { version = "0.4.9", path = "../vyn_types" }
