[package]
name = "kurai_error"
version = "0.4.9"
edition = "2024"

[dependencies]
colored = "3.0.0"
kurai_token = { version = "0.4.9", path = "../kurai_token" }
kurai_types = { version = "0.4.9", path = "../kurai_types" }
